name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Download Gradle Wrapper
      run: |
        wget https://services.gradle.org/distributions/gradle-7.0-bin.zip
        mkdir -p ~/.gradle/wrapper/dists/gradle-7.0-bin
        unzip -d ~/.gradle/wrapper/dists/gradle-7.0-bin gradle-7.0-bin.zip

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: app/build/outputs/apk/release/