name: Firefox VNC Server

on:
  workflow_dispatch:
  
jobs:
  setup-vnc:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg \
            lsb-release

      - name: Install Docker using official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh

      - name: Create Firefox User-Agent config
        run: |
          mkdir -p ~/firefox-config
          echo 'user_pref("general.useragent.override", "Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Mobile/15E148 Safari/604.1");' > ~/firefox-config/prefs.js

      - name: Run Firefox in Docker
        run: |
          docker run -d --name firefox \
            -e TZ=Asia/Hong_Kong \
            -e DISPLAY_WIDTH=1920 \
            -e DISPLAY_HEIGHT=1080 \
            -e KEEP_APP_RUNNING=1 \
            -e ENABLE_CJK_FONT=1 \
            -e VNC_PASSWORD=admin \
            -p 5800:5800 -p 5900:5900 \
            -v ~/firefox-config:/config/firefox:rw \
            --shm-size 2g \
            jlesage/firefox

      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Start Cloudflared
        run: |
          # 转发 noVNC 端口 5800
          cloudflared tunnel --url http://localhost:5800 &
          sleep 5
          
          # 获取并显示隧道URL
          echo "等待Cloudflared隧道URL..."
          sleep 10
          ps aux | grep cloudflared

      - name: Keep Alive and Monitor
        run: |
          echo "=== Firefox VNC Server Information ==="
          echo "noVNC端口: 5800"
          echo "VNC端口: 5900"
          echo "VNC密码: admin"
          echo "说明: 使用浏览器连接时，主机地址使用上面cloudflared生成的域名"
          echo "端口使用: 复制cloudflared URL后的端口号"
          
          while true; do
            echo "=== Status Update $(date) ==="
            docker ps
            sleep 300
          done